package cn.leafw.blog.springboot.thread.entity;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    private String user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.login_name
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    private String login_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_by
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    private String create_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_by
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    private String update_by;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public UserInfo(String user_id, String login_name, String password, String email, String create_by, Date create_time, String update_by, Date update_time) {
        this.user_id = user_id;
        this.login_name = login_name;
        this.password = password;
        this.email = email;
        this.create_by = create_by;
        this.create_time = create_time;
        this.update_by = update_by;
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public UserInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param user_id the value for user_info.user_id
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id == null ? null : user_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.login_name
     *
     * @return the value of user_info.login_name
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public String getLogin_name() {
        return login_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.login_name
     *
     * @param login_name the value for user_info.login_name
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public void setLogin_name(String login_name) {
        this.login_name = login_name == null ? null : login_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_by
     *
     * @return the value of user_info.create_by
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public String getCreate_by() {
        return create_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_by
     *
     * @param create_by the value for user_info.create_by
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public void setCreate_by(String create_by) {
        this.create_by = create_by == null ? null : create_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param create_time the value for user_info.create_time
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_by
     *
     * @return the value of user_info.update_by
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public String getUpdate_by() {
        return update_by;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_by
     *
     * @param update_by the value for user_info.update_by
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public void setUpdate_by(String update_by) {
        this.update_by = update_by == null ? null : update_by.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param update_time the value for user_info.update_time
     *
     * @mbggenerated Tue Nov 28 15:36:16 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}