spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lock_trans?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 20
    validationQuery: SELECT 1

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456